# Generated by Django 3.1.8 on 2021-04-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
